default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  # timeout: 5000

development:
  <<: *default
  database: bicycle_development
  host: localhost

test:
  <<: *default
  database: bicycle_test

production:
  <<: *default
  database: bicycle_production
  host: localhost
