# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf394cf85366ac8afcb908ac08dbda890bb1b83ed94b63b1e93755f25c95d794fb9b8eaca3ff95a6d6968d08f239dc17d0f54f966dbdb66e338eaea44f4b8e32

test:
  secret_key_base: 83e18cb3c563e24ffa630dce10f76fac6d26f70c4e3f3b2195cee27fb07ad8ed76e5823ff712ab3fd4c0bed55d2146d2520c800b22e129a30d9aa75b10622777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
